### ISSUE TITLE
How to change to preview position? 

### ISSUE THREAD

**Issue by KINGSABRI** [yaeda/inkdrop-preview-position#1]
Hi there
Thank you for making the plugin available 

How to change to preview position?

**Comment by yaeda** [comment]
Hi @KINGSABRI , you can change the position from the plugin settings.

![image](https://user-images.githubusercontent.com/819673/117780837-f4ef2680-b27a-11eb-9943-034ceecf3b24.png)

**Comment by KINGSABRI** [comment]
perfect, it works 
I it would be great if you put that in readme, if you would like

Thank you
